FROM node:20-alpine

WORKDIR /app

RUN apk --no-cache add --virtual builds-deps build-base python

# Copy package*.json files to correct locations
COPY /package*.json ./

# Install all dependencies needed for building
RUN npm ci
RUN npm rebuild bcrypt --build-from-source

ENV NODE_ENV production
ENV PORT 80
EXPOSE 80

COPY . .

CMD [ "npm", "run", "start:dev" ]
