version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: psephos:latest
    ports:
      - "8000:80"
    env_file:
      - ".env"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASS: postgres
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    restart: unless-stopped
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
