version: "3.8"

services:
  server:
    image: omjadas/psephos:latest
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
