FROM node:19-alpine

WORKDIR /app/client

RUN apk --no-cache add --virtual builds-deps build-base python git

COPY /client/package*.json ./

RUN npm ci

COPY ./scripts /app/
COPY ./.eslintrc.json /app/
COPY /client .

CMD [ "/app/entrypoint-client.sh" ]
