version: "3.7"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev-server
    image: psephos:latest
    ports:
      - "8000:80"
    env_file:
      - ".env"
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_NAME: postgres
      DB_PASS: postgres
    depends_on:
      - postgres
      - client
    volumes:
      - ./src:/app/src
      - ./schema.gql:/app/schema.gql
      - client:/app/client/build
    restart: unless-stopped
  
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev-client
    volumes:
      - ./client/src:/app/src
      - client:/app/build

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

volumes:
  client:
